export const PROJECT_CREATED = 'ProjectCreated'
export const PROJECT_DESCRIPTION_UPDATED = 'ProjectDescriptionUpdated'
export const PROJECT_LINK_UPDATED = 'ProjectLinkUpdated'
export const PROJECT_NAME_UPDATED = 'ProjectNameUpdated'
export const PROJECT_REVIEWED = 'ProjectReviewed'
export const PROJECT_PROMOTED = 'ProjectPromoted'
export const PROJECT_DELETED = 'ProjectDeleted'
export const PROJECT_RESUBMITTED = 'ProjectResubmitted'
export const PROJECT_REVIEWER_INVITED = 'ProjectReviewerInvited'
export const PROJECT_REVIEWER_REMOVED = 'ProjectReviewerRemoved'
export const PROJECT_REVIEWER_INVITATION_ACCEPTED = 'ProjectReviewerInvitationAccepted'
export const PROJECT_REVIEWER_INVITATION_EXPIRED = 'ProjectReviewerInvitationExpired'
export const PROJECT_REVIEWER_INVITATION_REJECTED = 'ProjectReviewerInvitationRejected'

export const PUBLICATION_CREATED = 'PublicationCreated'
export const PUBLICATION_CONDITIONS_UPDATED = 'PublicationConditionsUpdated'
