export default {
  PROJECT_CREATE_NOT_PERMITED: 'PROJECT_CREATE_NOT_PERMITED',
  PROJECT_DELETE_NOT_PERMITED: 'PROJECT_DELETE_NOT_PERMITED',
  REVIEWER_INVITE_NOT_PERMITED: 'REVIEWER_INVITE_NOT_PERMITED',
  PROJECT_REVIEW_NOT_PERMITED: 'PROJECT_REVIEW_NOT_PERMITED',
  PROJECT_UPDATE_NOT_PERMITED: 'PROJECT_UPDATE_NOT_PERMITED',
  INVALID_MEMBER_TYPE: 'INVALID_MEMBER_TYPE',
  INVALID_PROJECT_TYPE: 'INVALID_PROJECT_TYPE',
  INVALID_URL_TYPE: 'INVALID_URL_TYPE',
  INVALID_TITLE_TYPE: 'INVALID_TITLE_TYPE',
  INVALID_DESCRIPTION_TYPE: 'INVALID_DESCRIPTION_TYPE',
  INVALID_TIMESTAMP_TYPE: 'INVALID_TIMESTAMP_TYPE',
  INVALID_PUBLICATION_TYPE: 'INVALID_PUBLICATION_TYPE',
  INVALID_EVALUATION_TYPE: 'INVALID_EVALUATION_TYPE',
  INVALID_UUID_TYPE: 'INVALID_UUID_TYPE'
}
